# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0003_auto_20160518_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omniverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
