# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0012_weapon_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Power',
            new_name='SuperPower',
        ),
    ]
