# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0019_auto_20160520_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperPower',
            new_name='SuperPowers',
        ),
    ]
