# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0022_auto_20160520_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperHero',
            new_name='SuperHeroe',
        ),
    ]
