# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0033_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='abilities',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 42, 46, 849350, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='first_appearance',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 43, 7, 675111, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='group_affiliations',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 43, 40, 328561, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='height',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 43, 44, 904298, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='powers',
            field=models.TextField(default=datetime.datetime(2016, 5, 23, 14, 43, 47, 824173, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='real_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 43, 52, 511890, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='weight',
            field=models.CharField(default=datetime.datetime(2016, 5, 23, 14, 43, 56, 271561, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(),
        ),
    ]
