# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0034_auto_20160523_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='powers',
            field=models.CharField(max_length=128),
        ),
    ]
