# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0058_auto_20160530_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image1',
            field=models.ImageField(default=datetime.datetime(2016, 5, 30, 3, 27, 33, 759648, tzinfo=utc), upload_to='images/superheroes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Description'),
        ),
    ]
