# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0004_omniverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='multiuverse',
            field=models.ManyToManyField(to='HeroSandwich.Omniverse'),
        ),
        migrations.AddField(
            model_name='omniverse',
            name='multiuniverse',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 21, 37, 6, 737152, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
