# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0005_auto_20160518_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='multiuverse',
            new_name='multiuniverse',
        ),
        migrations.AlterField(
            model_name='omniverse',
            name='multiuniverse',
            field=models.CharField(max_length=15),
        ),
    ]
