# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0007_character_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='First_Appearance',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='eye_color',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hair_color',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='character',
            name='powers_weapons',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='real_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Weight'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='age'
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Born'),
        ),
    ]
