# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0008_auto_20160519_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superpower', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superpower', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='omniverse',
            name='multiuniverse',
            field=models.CharField(max_length=256),
        ),
    ]
