# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0009_auto_20160519_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='article_text',
            field=models.TextField(default=datetime.datetime(2016, 5, 19, 21, 2, 33, 705856, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 5, 19, 21, 2, 45, 952446, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
