# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0010_auto_20160519_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='article_text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='power',
            name='title',
        ),
    ]
