# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0011_auto_20160519_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 5, 19, 21, 38, 34, 97587, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
