# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0014_auto_20160519_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_power',
            new_name='SuperPower',
        ),
        migrations.RenameField(
            model_name='superpower',
            old_name='super_power',
            new_name='superpower',
        ),
    ]
