# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0015_auto_20160519_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='superpower',
            new_name='weapon',
        ),
    ]
