# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0018_superheropower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='superheropower',
            name='name',
        ),
        migrations.AddField(
            model_name='superheropower',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='superheropower',
            name='hero',
            field=models.ForeignKey(default=datetime.datetime(2016, 5, 20, 7, 24, 13, 177251, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.SuperHero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheropower',
            name='power',
            field=models.ForeignKey(default=datetime.datetime(2016, 5, 20, 7, 24, 25, 488608, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Power'),
            preserve_default=False,
        ),
    ]
