# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0020_auto_20160520_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.SuperHero')),
            ],
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='weapon',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='description',
        ),
        migrations.AddField(
            model_name='superheroweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Weapon'),
        ),
    ]
