# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0021_auto_20160520_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='multiuniverse',
        ),
        migrations.DeleteModel(
            name='Omniverse',
        ),
    ]
