# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0023_auto_20160520_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperHeroe',
            new_name='SuperHero',
        ),
    ]
