# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0024_auto_20160520_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='superhero',
            new_name='hero',
        ),
    ]
