# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0028_coloreye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='First_Appearance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='article_text',
        ),
        migrations.RemoveField(
            model_name='character',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='character',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created',
        ),
        migrations.RemoveField(
            model_name='character',
            name='current',
        ),
        migrations.RemoveField(
            model_name='character',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='height',
        ),
        migrations.RemoveField(
            model_name='character',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='character',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='character',
            name='powers_weapons',
        ),
        migrations.RemoveField(
            model_name='character',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='character',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='views',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='superheropower',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Character'),
        ),
        migrations.AlterField(
            model_name='superheroweapon',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Character'),
        ),
        migrations.DeleteModel(
            name='SuperHero',
        ),
    ]
