# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0029_auto_20160522_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
