# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0032_auto_20160522_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Character')),
            ],
        ),
    ]
