# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0044_auto_20160525_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='age_now',
            field=models.DateField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 5, 25, 22, 16, 3, 88818, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Description'),
        ),
    ]
