# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0049_auto_20160526_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='create',
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Description'),
        ),
        migrations.AlterField(
            model_name='description',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
