# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0055_auto_20160530_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photos',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 5, 30, 1, 53, 57, 377645, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Description'),
        ),
    ]
