# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSandwich', '0059_auto_20160530_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='image1',
        ),
        migrations.AddField(
            model_name='description',
            name='cover_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_photo', to='HeroSandwich.Photo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroSandwich.Description'),
        ),
    ]
